[PXZ-000] Update pom.xml
Problem:
	- java.lang.NoSuchMethodError: 'int io.jsonwebtoken.SignatureAlgorithm.getMinKeyLength()'
	- no need to have also jjwt dependency

Implement:
	- delete
		<dependency>
    			<groupId>io.jsonwebtoken</groupId>
    			<artifactId>jjwt</artifactId>
    			<version>0.9.1</version>
		</dependency>